inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - ".git/**/*"
  NewCops: disable
  TargetRubyVersion: 3.2

#
# RuboCop built-in settings.
#   For documentation on all settings see: https://docs.rubocop.org/en/stable
#

# Trailing periods.
Layout/DotPosition:
  Description: Checks the position of the dot in multi-line method calls.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-multi-line-chains
  Enabled: true
  EnforcedStyle: leading

# Turn on auto-correction of equals alignment.
Layout/EndAlignment:
  AutoCorrect: true

# Prevent accidental windows line endings
Layout/EndOfLine:
  EnforcedStyle: lf

# Use a table layout for hashes
Layout/HashAlignment:
  Description: Align the elements of a hash literal if they span more than one line.
  Enabled: true
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

# Match existing layout
Layout/SpaceInsideHashLiteralBraces:
  Description: Use spaces inside hash literal braces - or don't.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#spaces-operators
  Enabled: true
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SupportedStyles:
    - space
    - no_space

# Support long block lengths for tests
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

# Soften limits
Metrics/ClassLength:
  Max: 250
  Exclude:
    - "spec/**/*"

# Soften limits
Metrics/MethodLength:
  Max: 50

# Soften limits
Metrics/ModuleLength:
  Max: 250

Metrics/ParameterLists:
  CountKeywordArgs: false

# Needed for testing DateTime
# Style/DateTime:
#   Exclude: ["spec/**/*"]

Style/Documentation:
  Enabled: true

# One line methods
Style/EmptyMethod:
  EnforcedStyle: expanded

# Ruby 3 compatibility feature
Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  AutoCorrect: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/HashSyntax:
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#hash-literals
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: never

Style/Encoding:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/SymbolArray:
  Description: Use %i or %I for arrays of symbols.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#percent-i
  Enabled: false

Metrics/CyclomaticComplexity:
  Description: A complexity metric that is strongly correlated to the number of test cases needed to validate a method.
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Layout/LineLength:
  Description: Limit lines to 180 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 180
  AllowURI: true
  Exclude:
    - 'spec/**/*'

Style/NumericLiterals:
  Description: Add underscores to large numeric literals to improve their readability.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#underscores-in-numerics
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false